[tool.black]
line-length = 79
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
(
  /migrations/   # Django DB migrations
  | settings.py
)
'''

[tool.isort]
profile = 'black'
combine_as_imports = true
include_trailing_comma = true
line_length = 79
multi_line_output = 3
lines_between_types = 1
lines_after_imports = 2
skip_gitignore = true
skip_glob = ['*/migrations/*', '*/settings.py']
known_first_party = ['config']
known_third_party = ['rest_framework', 'django', 'rest_framework_simplejwt', 'drf_yasg']
