# Generated by Django 5.0.4 on 2024-06-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collects", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collect",
            name="current_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Текущая сумма",
            ),
        ),
        migrations.AlterField(
            model_name="collect",
            name="goal_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Целевая сумма",
            ),
        ),
    ]
